#!/usr/bin/perl

while(<>) {
    #
    # Only work on lines with the file name
    #
    if(m/\//) {

	#
	# Pull out Artist, Album, Track Name
	#
 	if(m/\/([^\/]+)\/([^\/]+)\/([^\/]+)\:\s*$/) {
	    ($artist, $album, $track) = ($1, $2, $3);

	    $cue = `grep '\/${album}' /usr/local/Music/pidap.generated.playlist`;
	    if($cue =~ m/\s+(\d+)/) {
		$cue_num = $1;
	    }

	    print "\n";
	    print "$artist\n";
	    print "${cue_num}: ${album}\n";
	    print "$track\n";
	}
    }
}
    
