#!/usr/bin/perl


use POSIX ":sys_wait_h";
use Getopt::Std;
use Time::HiRes;
use FindBin;
use lib "$FindBin::Bin/lib";
use PIDAPAlbum qw(get_album_offsets read_current_album build_resume_cmd write_current_album);


$usage =
    "landap [-c <category>] [-a <artist>] [-l <album>] [-m <mount>] [-p] [-q] [-r]\n" .
    "\n" .
    "<category>, <artist>, and <album> arguments can be perl regex or simple string\n" .
    "\n" .
    "In program control keys:\n\n" .
    "   n - Next LP\n" .
    "   t - Next Track\n" .
    "   m - Menu\n" .
    "   x - Exit\n" .
    "\n\n";

getopts("a:c:hl:m:pqr");

if(defined($opt_h)) {
   print $usage;
   exit;
}


if(defined($opt_m)) {
   $mount = $opt_m;
} else {
   $mount = "/mnt/wd_my_cloud";
}



######################################################################
#
#
#
$run = 1;
$pid = 0;
$first_lp = 0;

@artists = ();
@categories = ();
@albums = ();

@play_artists = ();
@play_categories = ();
@play_albums = ();

my $RUN_DIR = $FindBin::Bin;
my $playlist_file = "$RUN_DIR/landap.generated.playlist";
my $current_album_file = "$RUN_DIR/landap.generated.current_album";
my $resume_file = "$RUN_DIR/landap.generated.resume";
my $menu_in_fifo = "$RUN_DIR/landap.generated.menu_in";
my $menu_out_fifo = "$RUN_DIR/landap.generated.menu_out";

#
# Create menu FIFOs and start the standalone menu process.
#
for my $f ($menu_in_fifo, $menu_out_fifo) {
    if (-e $f && !-p $f) {
        unlink($f);
    }
    unless (-p $f) {
        POSIX::mkfifo($f, 0666) or die "cannot create FIFO $f: $!\n";
    }
}

my $menu_pid = fork;
die "Failed to fork landap-menu\n" unless defined $menu_pid;
if ($menu_pid == 0) {
    exec("perl", "$FindBin::Bin/landap-menu") or die "exec landap-menu: $!\n";
}


#
# Directory structure organization:
#
#   Music/<Category>/<Artist>/<Album>/<Track>.flac
#
while($run) {

   print("Building Album List");

   #
   # Check category directories
   #
   foreach $category (`ls $mount/`) {
      chomp($category);

      #
      # List of all categories for manipulating play list later.
      #
      push(@categories, $category);

      #
      # List of categories to play now.
      #
      if(!defined($opt_c) || ($category =~ m/$opt_c/)) {
	 $play_categories{$category} = $category;
	 push(@play_categories, $category);
      }


      #
      # Check artist directories
      #
      foreach $artist (`ls $mount/$category/`) {
	 chomp($artist);

	 #
	 # List of all artists
	 #
	 push(@artists, $artist);

	 #
	 # If -a option only want to play artists matching name..
	 # List of artists to play now.
	 #
	 if(defined($play_categories{$category}) &&
	     (!defined($opt_a) || ($artist =~ m/$opt_a/))) {

	    $play_artists{$artist} = $artist;
	    push(@play_artists, $artist);
	 }


	 #
	 # Check album directories
	 #
	 foreach $album (`ls $mount/$category/$artist`) {
	    print(".");

	    chomp($album);

	    #
	    # For multi-disk albums, only remember disc 1.
	    # Play multi-disk albums all together later...
	    #
	    if($album =~ m/dis[ck]_?(\d+)/i) {
	       $disk_num = $1;
	       next unless($disk_num =~ m/0*1/);
	    }

	    #
	    # All Album names
	    #
	    push(@album_names, $album);

	    $album_path = "${mount}/${category}/${artist}/${album}";

	    #
	    # Build lists of albums.
	    #
	    push(@{$albums{$category}}, $album_path);
	    push(@{$albums{$artist}}, $album_path);

	    #
	    # List of album full paths.
	    #
	    push(@albums, $album_path);

	    #	    $last_track = `ls $album_path | tail -1`;
	    #	    $last_track{$album_path} = "${mount}/${category}/${artist}/${album}/${last_track}";

	    #
	    # -l option only play matching albums.
	    #
	    if(defined($play_categories{$category}) && defined($play_artists{$artist})) {
	       if(!defined($opt_l) || ($album =~ m/$opt_l/)) {
		  push(@play_albums, "${mount}/${category}/${artist}/${album}");
	       }
	    }
	 }
      }
   }

   #
   # Start streaming albums
   #
   print("\n\n======================== YASS! ================================\n\n");

   #
   # Randomize array
   #
   if(defined($opt_r)) {
      @play_albums = &rand_array(@play_albums);
   }

   #
   # Print out cuesheet unless quiet mode.
   #
   unless(defined($opt_q)) {

      open(CUEFILE, ">CUESHEET.txt") or
	  die "unable to open CUESHEET.txt\n";

      foreach $jj (0 .. $#play_albums) {
	 printf("CUESHEET:%7d %s\n", $jj, $play_albums[$jj]);
	 printf(CUEFILE "CUESHEET:%7d %s\n", $jj, $play_albums[$jj]);
      }
      close(CUEFILE);
   }

   #
   # Write generated playlist for the menu.
   #
   if (open(my $pf, '>', $playlist_file)) {
      for my $p (@play_albums) {
         print $pf "$p\n";
      }
      close($pf);
   }

   &play_albums(@play_albums);

   last if(defined($opt_p));
}


#
#
#
sub play_albums() {

   my (@albums) = (@_);

   my @albums_0 = @albums;

   #
   # Loop through albums and play all tracks in album folder.
   #
   while(1) {
   for ($ii = $first_lp; $ii <= $#albums; $ii++) {
      my $play_album = $albums[$ii];
      my $use_resume = 0;
      my $resume_offset = 0;

      #
      # Check for a resume request from the menu.
      #
      if (-e $resume_file) {
         my ($ralbum, $roffset) = ('', 0);
         if (open(my $rf, '<', $resume_file)) {
            while (<$rf>) {
               chomp;
               if (/^album=(.+)/) {
                  $ralbum = $1;
               } elsif (/^offset=([0-9.]+)/) {
                  $roffset = $1;
               }
            }
            close($rf);
         }
         unlink($resume_file);
         for my $j (0 .. $#albums) {
            if ($albums[$j] eq $ralbum) {
               $ii = $j;
               $play_album = $albums[$j];
               $use_resume = 1;
               $resume_offset = $roffset;
               last;
            }
         }
      }

      print("Album Name: $play_album\n");

      #
      # Does this album end with disk_<n>?
      # Cut off the disk number and play them all
      #
      if($play_album =~ m/(dis(c|k)_?(\d+))/i) {
	 ($disc_name, $ck, $disc_num) = ($1, $2, $3);

	 print("DISC_NAME=$disc_name DISC_NUM=$disc_num\n");

	 $play_album =~ s/$disc_num//;
      }

      my ($files, $durations, $offsets, $total) = get_album_offsets($play_album);
      my $start_offset = $resume_offset;
      write_current_album($play_album, $start_offset, $files, $durations, $current_album_file);

      my $cmd;
      if ($use_resume) {
         $cmd = build_resume_cmd($play_album, $resume_offset, $files, $durations);
      }
      unless (defined $cmd) {
         $cmd = "play ${play_album}*/*.flac";
      }

      unless(defined($opt_p)) {
	 #
	 # Fork off process to stream music.
	 # Use <Album_Name>*/*.flac to catch all disc numbers.
	 #
	 $play_id = &print_run($cmd);

	 #
	 # Fork process to wait for user input
	 #
	 $input_id = &input_handler($$, $play_id);

	 #
	 # Wat for streaming to finish for this lp
	 #
	 waitpid $play_id, 0;

	 #
	 # Kill input handler for this lp
	 # Next lp will get a new input handler
	 # (and a new PID to send signals)
	 #
	 kill 9, $input_id;
	 waitpid $input_id, 0;
      }
   }
   }
}

#
# Fork process to wait for keyboard input.
# Send signals to play process for next track, etc.
#
sub input_handler() {
   ($parent_id, $play_id) = (@_);

   my $pid = fork;
   die "Failed for fork input handler\n" unless defined $pid;

   #
   # Child Process Only
   #
   if($pid == 0) {
      #
      #
      # x = exit
      # n = next album in queue
      # t = next track on album
      # m = menu
      #
      my $key_pressed = 'c';
      while(1) {

	 #
	 # Child process - Wait for one key input.
	 #
	 $key_pressed = read_key();

	 if($key_pressed) {

	    print("KEY PRESSED:$key_pressed PARENT=$parent_id, PLAY_ID=$play_id\n");

	    #
	    # x for exit. Kill parent process.
	    #
	    if($key_pressed eq 'x' || $key_pressed eq 'X') {

	       print("Killing:$parent_id\n");
	       kill 9, -$play_id;
	       kill 9, $parent_id;
	       exit;
	    }
	    #
	    # n for next album. Kill SoX process group
	    # Loop around and pick up next lp
	    #
	    elsif($key_pressed eq 'n' || $key_pressed eq 'N') {
	       print("Next Album\n");
	       kill 9, -$play_id;
	       exit;
	    }
	    #
	    # Next track - send Ctrl-C to SoX to skip to next track.
	    #
	    elsif($key_pressed eq 't' || $key_pressed eq 'T') {
	       print("Next Track\n");

	       #
	       # Send Ctrl-C to the playback process group
	       #
	       kill 2, -$play_id;

	       #
	       # Wait a little bit to prevent user from sending 2
	       # Ctrl-C in a row. 2x Ctrl-C kills sox, 1x Ctrl-C
	       # skips to next track
	       # 
	       Time::HiRes::usleep(1200);
	    }
	    #
	    # m for menu
	    #
	    elsif($key_pressed eq 'm' || $key_pressed eq 'M') {
	       if (open(my $mf, '>', $menu_in_fifo)) {
          print $mf "show\n";
          close($mf);
       }
       if (open(my $of, '<', $menu_out_fifo)) {
          my $ralbum = '';
          my $roffset = 0;
          my $cancel = 0;
          while (<$of>) {
             chomp;
             if (/^album=(.+)/) {
                $ralbum = $1;
             } elsif (/^offset=([0-9.]+)/) {
                $roffset = $1;
             } elsif (/^cancel=1/) {
                $cancel = 1;
             }
          }
          close($of);
          if ($cancel) {
             next;
          }
          if ($ralbum) {
             if (open(my $rf, '>', $resume_file)) {
                print $rf "album=$ralbum\noffset=$roffset\n";
                close($rf);
             }
             kill 9, -$play_id;
             exit;
          }
       }
	    }
	 }
      }
      exit;
   }
   #
   # Main process. Return spawned PID number.
   #
   else {
      return $pid;
   }
}


#
# Print command and system run it.
#
sub print_run() {
   ($cmd) = (@_);

   #
   #
   #
   print("$cmd\n");

   my $pid = fork;
   die "Failed to fork $!\n" unless defined $pid;

   #
   # Child process only.
   #
   if($pid == 0) {

      setpgrp(0, 0);
      system($cmd);
      exit;
   }

   #
   # Main process, pass back new child PID
   #
   return $pid;
}


#
# Randomize array order.
# Thanks to Perl.LiveJournal.com
# https://perl.livejournal.com/101830.html
#
sub rand_array {
   my @array = @_;
   my @rand;
   while (@array) {
      my $i = int(rand(@array));
      my $random_item = $array[$i];
      push @rand, $random_item;
      splice(@array, $i, 1);
   }
   return @rand;
}


#
# Terminal helpers and menu
#
sub set_raw {
   system('stty', 'raw', '-echo', 'min', '1', 'time', '0');
}

sub restore_term {
   system('stty', 'sane');
}

sub timed_read_byte {
   my ($timeout) = @_;
   my $rin = '';
   vec($rin, fileno(STDIN), 1) = 1;
   my $rout = $rin;
   my $nfound = select($rout, undef, undef, $timeout);
   return undef if $nfound <= 0;
   my $c;
   my $n = sysread(STDIN, $c, 1);
   return undef unless $n;
   return $c;
}

sub read_key {
   set_raw();
   my $c;
   my $n = sysread(STDIN, $c, 1);
   my $key = $c;
   if ($n && $c eq "\e") {
      my $c2 = timed_read_byte(0.1);
      if (defined $c2 && $c2 eq '[') {
         my $c3 = timed_read_byte(0.1);
         if (defined $c3) {
            if ($c3 eq 'A') { $key = 'UP'; }
            elsif ($c3 eq 'B') { $key = 'DOWN'; }
            elsif ($c3 eq 'C') { $key = 'RIGHT'; }
            elsif ($c3 eq 'D') { $key = 'LEFT'; }
            else { $key = 'ESC'; }
         } else {
            $key = 'ESC';
         }
      } else {
         $key = 'ESC';
      }
   }
   restore_term();
   return $key;
}
