#!/usr/bin/perl

use FindBin;
use lib "$FindBin::Bin/lib";
use Time::HiRes;
use IO::Select;
use POSIX;
use Fcntl;
use PIDAPAlbum qw(get_album_offsets read_current_album);
use PIDAPRand;

my $MENU_COLUMNS = 24;
my $MENU_ITEM_MAX  = $MENU_COLUMNS - 1;
my $HSCROLL_INTERVAL = 0.35;
my $NAV_COOLDOWN = $ENV{PIDAP_MENU_NAV_COOLDOWN} || 0.15;

my $RUN_DIR = $ENV{PIDAP_RUN_DIR};
if (!$RUN_DIR && $ENV{PIDAP_PID_FILE}) {
    ($RUN_DIR = $ENV{PIDAP_PID_FILE}) =~ s{[^/]+$}{};
}
$RUN_DIR ||= $FindBin::Bin;
my $last_nav_time = 0;
if ($ENV{PIDAP_RUN_DIR} && !-d $RUN_DIR) {
    system('mkdir', '-p', $RUN_DIR) == 0 or die "cannot create $RUN_DIR: $!\n";
}

my $DATA_DIR = $ENV{PIDAP_DATA_DIR} || $RUN_DIR;
if ($ENV{PIDAP_DATA_DIR} && !-d $DATA_DIR) {
    system('mkdir', '-p', $DATA_DIR) == 0 or die "cannot create $DATA_DIR: $!\n";
}

my $playlist_file       = "$DATA_DIR/pidap.generated.playlist";
my $current_album_file  = "$DATA_DIR/pidap.generated.current_album";
my $display_buffer_file = "$RUN_DIR/pidap.generated.display";
my $menu_mode_file      = "$RUN_DIR/pidap.generated.menu_mode";
my $menu_in_fifo        = "$RUN_DIR/pidap.generated.menu_in";
my $menu_out_fifo       = "$RUN_DIR/pidap.generated.menu_out";
my $play_pid_file       = "$RUN_DIR/pidap.generated.play_pid";

sub log_warn {
    my ($msg) = @_;
    print STDERR "pidap-menu: $msg\n";
}

sub restart_playback {
    return unless -r $play_pid_file;
    if (open(my $pf, '<', $play_pid_file)) {
        my $pid = <$pf>;
        close($pf);
        chomp($pid) if defined $pid;
        if ($pid && $pid =~ /^\d+$/ && kill(0, $pid)) {
            # Kill the current play process; pidap will see it exit and
            # restart from the beginning of the newly generated playlist.
            kill('TERM', $pid);
        }
    }
}

END {
    # Always clean up the menu-mode flag if we exit for any reason.
    unlink($menu_mode_file) if -e $menu_mode_file;
}

# Create the FIFOs on startup if they do not already exist.
for my $f ($menu_in_fifo, $menu_out_fifo) {
    if (-e $f && !-p $f) {
        unlink($f);
    }
    unless (-p $f) {
        if (!POSIX::mkfifo($f, 0666)) {
            log_warn("cannot create FIFO $f: $!");
        }
    }
}

sub read_playlist_file {
    my ($file) = @_;
    my @paths = ();
    if (open(my $pf, '<', $file)) {
        while (<$pf>) {
            chomp;
            next unless $_;
            if (m/^\s*(?:CUESHEET:\s*)?\d+\s+(.+)$/) {
                push @paths, $1;
            } elsif (m/^(.+)$/) {
                push @paths, $1;
            }
        }
        close($pf);
    }
    return @paths;
}


sub display_menu_list {
    my ($title, $items_ref, $selected, $visible_lines, $full) = @_;
    $full = 1 unless defined $full;
    $visible_lines ||= 10;
    $selected = 0 if $selected < 0;
    $selected = $#$items_ref if $selected > $#$items_ref;

    my $total = scalar(@$items_ref);
    my $item_lines = $visible_lines - ($title ? 1 : 0);
    $item_lines = 1 if $item_lines < 1;

    my $center_line = 7;
    my $center_pos = $center_line - ($title ? 2 : 1);
    $center_pos = 0 if $center_pos < 0;
    $center_pos = $item_lines - 1 if $center_pos >= $item_lines;

    my $top = 0;
    if ($total > $item_lines) {
        $top = $selected - $center_pos;
        $top = 0 if $top < 0;
        $top = $total - $item_lines if $top > $total - $item_lines;
    }

    my $title_max = $MENU_COLUMNS;
    my $item_max = $MENU_ITEM_MAX;

    if (open(my $fh, '>', '/dev/tty1')) {
        if ($full) {
            if (!$title && $total == 0) {
                print $fh "\e[2J\e[H";
            } else {
                print $fh "\e[H";
            }
            if ($title) {
                my $t = (length($title) > $title_max) ? substr($title, 0, $title_max) : $title;
                printf $fh "\e[32m%-*s\e[0m\n", $title_max, $t;
            }
            my $end = $top + $item_lines - 1;
            for my $i ($top .. $end) {
                my $item = ($i <= $#$items_ref) ? $items_ref->[$i] : '';
                $item = substr($item, 0, $item_max) if length($item) > $item_max;
                my $nl = ($i == $end) ? '' : "\n";
                if ($i == $selected) {
                    printf $fh "\e[1m>%-*s\e[0m$nl", $item_max, $item;
                } else {
                    printf $fh " %-*s$nl", $item_max, $item;
                }
            }
        } else {
            my $row = ($selected - $top) + ($title ? 2 : 1);
            my $item = $items_ref->[$selected] // '';
            $item = substr($item, 0, $item_max) if length($item) > $item_max;
            print $fh "\e[$row;1H";
            printf $fh "\e[1m>%-*s\e[0m", $item_max, $item;
        }
        close($fh);
    } else {
        log_warn("cannot write to /dev/tty1: $!");
    }
}

sub update_display {
    my ($album_number, $album_path, $track_file, $album_count) = @_;
    return unless defined $album_number && $album_path && $track_file;

    my @parts = split(m{/}, $album_path);
    return if @parts < 2;
    my $album_name = $parts[-1];
    my $artist_name = $parts[-2];

    my $track_name = $track_file;
    $track_name =~ s{^.*/}{};
    $track_name =~ s{\.(?:flac|mp3|ogg|m4a|wav|gsm|amr)$}{}i;

    my $count_str = (defined $album_count && $album_count > 0) ? "/$album_count" : '';
    if (open(my $df, '>', $display_buffer_file)) {
        print $df "\n$artist_name\n";
        print $df "$album_number$count_str: $album_name\n";
        print $df "$track_name\n";
        close($df);
    }
    &restore_display();
}

sub restore_display {
    return unless -r $display_buffer_file;
    my @lines;
    if (open(my $df, '<', $display_buffer_file)) {
        chomp(@lines = <$df>);
        close($df);
    }
    return unless @lines;
    if (open(my $fh, '>', '/dev/tty1')) {
        print $fh "\e[2J\e[H";
        for my $l (@lines) {
            print $fh "$l\n";
        }
        close($fh);
    }
}

sub run_menu {
    my ($albums_ref, $current_album_idx) = @_;

    my @albums = @$albums_ref;
    my $no_albums = !@albums;
    $current_album_idx = 0 if !$no_albums && ($current_album_idx < 0 || $current_album_idx > $#albums);

    my ($current_album, $current_offset) = read_current_album($current_album_file);
    $current_offset ||= 0;

    # Group albums by parent directory (artist).
    my %artist_paths;
    my %artist_albums;
    for my $i (0 .. $#albums) {
        my $p = $albums[$i];
        my $parent = ($p =~ m{^(.*)/[^/]+$}) ? $1 : '';
        $artist_paths{$parent} = 1 if $parent;
        push @{$artist_albums{$parent}}, $i;
    }
    my @artists = sort { (my $aa = $a) =~ s{^.*/}{}; (my $bb = $b) =~ s{^.*/}{}; $aa cmp $bb } keys %artist_paths;
    my %artist_to_idx;
    for my $i (0 .. $#artists) {
        $artist_to_idx{$artists[$i]} = $i;
    }
    for my $artist (keys %artist_albums) {
        $artist_albums{$artist} = [ sort { my $aa = $albums[$a]; $aa =~ s{^.*/}{}; my $bb = $albums[$b]; $bb =~ s{^.*/}{}; $aa cmp $bb } @{$artist_albums{$artist}} ];
    }
    my @artist_album_lists = map { $artist_albums{$_} } @artists;

    # Group artists by parent directory (genre).
    my %genre_paths;
    my %genre_artists;
    for my $artist (@artists) {
        my $parent = ($artist =~ m{^(.*)/[^/]+$}) ? $1 : '';
        $genre_paths{$parent} = 1 if $parent;
        push @{$genre_artists{$parent}}, $artist;
    }
    my @genres = sort { (my $aa = $a) =~ s{^.*/}{}; (my $bb = $b) =~ s{^.*/}{}; $aa cmp $bb } keys %genre_paths;
    for my $genre (keys %genre_artists) {
        $genre_artists{$genre} = [ sort { (my $aa = $a) =~ s{^.*/}{}; (my $bb = $b) =~ s{^.*/}{}; $aa cmp $bb } @{$genre_artists{$genre}} ];
    }
    my @genre_artist_lists = map { $genre_artists{$_} } @genres;

    my $current_genre_idx = 0;
    my $current_artist_in_genre_idx = 0;
    my $current_artist_idx = 0;
    my $current_album_in_artist_idx = 0;
    for my $gi (0 .. $#genres) {
        my $artists_for = $genre_artist_lists[$gi];
        for my $j (0 .. $#$artists_for) {
            my $ai = $artist_to_idx{$artists_for->[$j]};
            my $albums_for = $artist_album_lists[$ai];
            for my $k (0 .. $#$albums_for) {
                if ($albums_for->[$k] == $current_album_idx) {
                    $current_genre_idx = $gi;
                    $current_artist_in_genre_idx = $j;
                    $current_artist_idx = $ai;
                    $current_album_in_artist_idx = $k;
                    last;
                }
            }
        }
    }

    my ($track_files, $track_durations, $track_offsets);
    my $current_track_idx = 0;
    if ($no_albums) {
        $track_files = [];
        $track_durations = [];
        $track_offsets = [];
    } else {
        ($track_files, $track_durations, $track_offsets) = &get_album_offsets($albums[$current_album_idx]);
        if ($track_durations && @$track_durations) {
            my $cum = 0;
            for my $i (0 .. $#$track_durations) {
                $cum += $track_durations->[$i];
                if ($cum > $current_offset) {
                    $current_track_idx = $i;
                    last;
                }
            }
        }
    }
    my $current_track_file = $track_files->[$current_track_idx] // '';

    my $genre_idx = $current_genre_idx;
    my $artist_in_genre_idx = $current_artist_in_genre_idx;
    my $artist_idx = $current_artist_idx;
    my $album_in_artist_idx = $current_album_in_artist_idx;
    my $album_idx = $current_album_idx;
    my $track_album_idx = $album_idx;
    my $level = $no_albums ? 0 : 3;
    my $selected = $no_albums ? 0 : $current_track_idx;
    my @items;
    my $title = '';
    my $did_select = 0;

    my $hscroll_offset = 0;
    my $hscroll_dir = 1;
    my $hscroll_selected = -1;
    my $hscroll_last = 0;

    my $in_system = 0;
    my $in_playlist = 0;
    my $in_playlist_menu = 0;
    my $playlist_album_idx = $current_album_idx;
    my $top_selected = $current_genre_idx + 2;

    my $sel = IO::Select->new(\*MENU_IN);

    # Signal that the menu is now active.
    if (open(my $mm, '>', $menu_mode_file)) {
        close($mm);
    } else {
        log_warn("cannot create $menu_mode_file: $!");
    }

    while (1) {
        if ($in_playlist_menu) {
            @items = ('Browse Playlist', 'Restart List Jump', 'Random List Jump', 'Generate Random Playlist', 'Generate Alpha-numeric Playlist');
            $title = 'Playlist';
        } elsif ($in_system) {
            @items = ('Generate Logs');
            $title = 'System';
        } elsif ($level == 0) {
            @items = ('System', 'Playlist', map { my $p = $_; $p =~ s{^.*/}{}; $p; } @genres);
            $title = '';
        } elsif ($level == 1) {
            my $artists_for = $genre_artist_lists[$genre_idx];
            @items = map { my $p = $_; $p =~ s{^.*/}{}; $p; } @$artists_for;
            $title = $genres[$genre_idx];
            $title =~ s{^.*/}{};
        } elsif ($level == 2) {
            if ($in_playlist) {
                my @albums_for = (0 .. $#albums);
                @items = map { my $p = $albums[$_]; $p =~ s{^.*/}{}; $p; } @albums_for;
                $title = 'Playlist';
            } else {
                my $albums_for = $artist_album_lists[$artist_idx];
                @items = map { my $p = $albums[$_]; $p =~ s{^.*/}{}; $p; } @$albums_for;
                $title = $artists[$artist_idx];
                $title =~ s{^.*/}{};
            }
        } else {
            if ($track_album_idx != $album_idx) {
                my $album = $albums[$album_idx];
                ($track_files, $track_durations, $track_offsets) = &get_album_offsets($album);
                $track_album_idx = $album_idx;
            }
            unless ($track_files && @$track_files) {
                $level = 2;
                $selected = $album_in_artist_idx;
                next;
            }
            @items = map { my $f = $_; $f =~ s{^.*/}{}; $f; } @$track_files;
            $title = $albums[$album_idx];
            $title =~ s{^.*/}{};
        }

        if ($selected != $hscroll_selected) {
            $hscroll_offset = 0;
            $hscroll_dir = 1;
            $hscroll_selected = $selected;
            $hscroll_last = Time::HiRes::time();
        }
        my @display_items = @items;
        if (length($items[$selected]) > $MENU_ITEM_MAX) {
            my $max_offset = length($items[$selected]) - $MENU_ITEM_MAX;
            $hscroll_offset = $max_offset if $hscroll_offset > $max_offset;
            $display_items[$selected] = substr($items[$selected], $hscroll_offset, $MENU_ITEM_MAX);
        }
        &display_menu_list($title, \@display_items, $selected, 13);

        my $action = '';
        while (!$action) {
            my @ready = $sel->can_read($HSCROLL_INTERVAL);
            my $now = Time::HiRes::time();
            if ($now - $hscroll_last >= $HSCROLL_INTERVAL) {
                my $item_len = length($items[$selected]);
                if ($item_len > $MENU_ITEM_MAX) {
                    my $max_offset = $item_len - $MENU_ITEM_MAX;
                    $hscroll_offset += $hscroll_dir;
                    if ($hscroll_offset >= $max_offset) {
                        $hscroll_offset = $max_offset;
                        $hscroll_dir = -1;
                    } elsif ($hscroll_offset <= 0) {
                        $hscroll_offset = 0;
                        $hscroll_dir = 1;
                    }
                    @display_items = @items;
                    $display_items[$selected] = substr($items[$selected], $hscroll_offset, $MENU_ITEM_MAX);
                    &display_menu_list($title, \@display_items, $selected, 13, 0);
                }
                $hscroll_last = $now;
            }
            if (@ready) {
                my $line = <MENU_IN>;
                next unless defined $line;
                chomp $line;
                $line =~ s/^\s+|\s+$//g;
                if ($line =~ /^(up|down|select|back)$/) {
                    if ($line =~ /^(up|down)$/ && Time::HiRes::time() - $last_nav_time < $NAV_COOLDOWN) {
                        log_warn("ignoring $line: nav cooldown");
                    } else {
                        $action = $line;
                        $last_nav_time = Time::HiRes::time() if $line =~ /^(up|down)$/;
                        log_warn("menu action: $action");
                    }
                } elsif ($line eq 'show') {
                    # Already in the menu; continue the existing action loop.
                }
            }
        }

        if (!$action) {
            last;
        } elsif ($action eq 'back') {
            if ($in_playlist_menu) {
                $in_playlist_menu = 0;
                $level = 0;
                $selected = 1;
                next;
            } elsif ($in_system) {
                $in_system = 0;
                $level = 0;
                $selected = 0;
                next;
            } elsif ($level == 0) {
                last;
            } elsif ($level == 1) {
                $level = 0;
                $selected = $top_selected;
                next;
            } elsif ($level == 2) {
                if ($in_playlist) {
                    $level = 0;
                    $in_playlist = 0;
                    $in_playlist_menu = 1;
                    $selected = 0;
                } else {
                    $selected = $album_in_artist_idx;
                    $level = 1;
                }
                next;
            } elsif ($level == 3) {
                if ($in_playlist) {
                    $level = 2;
                    $selected = $playlist_album_idx;
                } else {
                    $selected = $album_in_artist_idx;
                    $level = 2;
                }
                next;
            }
        } elsif ($action eq 'up') {
            $selected = ($selected > 0) ? $selected - 1 : $#items;
        } elsif ($action eq 'down') {
            $selected = ($selected < $#items) ? $selected + 1 : 0;
        } elsif ($action eq 'select') {
            if ($in_playlist_menu) {
                if ($selected == 0) {
                    # Browse Playlist: show the album/track list
                    $in_playlist = 1;
                    $level = 2;
                    $playlist_album_idx = $current_album_idx;
                    $album_idx = $playlist_album_idx;
                    $selected = $playlist_album_idx;
                } elsif ($selected == 1) {
                    # Restart List: jump to the first album/track
                    $album_idx = 0;
                    $selected = 0;
                    ($track_files, $track_durations, $track_offsets) = &get_album_offsets($albums[$album_idx]);
                    $track_album_idx = $album_idx;
                    $did_select = 1;
                    last;
                } elsif ($selected == 2) {
                    # Random List: jump to a random album, track 0
                    $album_idx = int(rand(scalar(@albums)));
                    $selected = 0;
                    ($track_files, $track_durations, $track_offsets) = &get_album_offsets($albums[$album_idx]);
                    $track_album_idx = $album_idx;
                    $did_select = 1;
                    last;
                } elsif ($selected == 3) {
                    &display_menu_list('Generating...', ['Generate Random Playlist'], 0, 13);
                    system('perl', "$FindBin::Bin/pidap-playlist", '-r') == 0
                        or log_warn('pidap-playlist -r failed');
                    &display_menu_list('Done', ['Random Playlist Location'], 0, 13);
                    sleep 1;
                    &restart_playback();
                    last;
                } else {
                    &display_menu_list('Generating...', ['Generate Alpha-numeric Playlist'], 0, 13);
                    system('perl', "$FindBin::Bin/pidap-playlist", '-s') == 0
                        or log_warn('pidap-playlist -s failed');
                    &display_menu_list('Done', ['Alpha-Numeric Playlist'], 0, 13);
                    sleep 1;
                    &restart_playback();
                    last;
                }
            } elsif ($in_system) {
                &display_menu_list('Collecting...', ['Generate Logs'], 0, 13);
                my $log_dir = `"$FindBin::Bin/pidap-logs"`;
                chomp($log_dir) if defined $log_dir;
                $log_dir ||= 'unknown';
                &display_menu_list('Done', ["Logs: $log_dir"], 0, 13);
                sleep 1;
                last;
            } elsif ($level == 0) {
                if ($selected == 0) {
                    $in_system = 1;
                    $selected = 0;
                } elsif ($selected == 1) {
                    $in_playlist_menu = 1;
                    $selected = 0;
                } else {
                    $genre_idx = $selected - 2;
                    $top_selected = $selected;
                    $level = 1;
                    $artist_in_genre_idx = ($genre_idx == $current_genre_idx) ? $current_artist_in_genre_idx : 0;
                    $selected = $artist_in_genre_idx;
                }
            } elsif ($level == 1) {
                $artist_in_genre_idx = $selected;
                $artist_idx = $artist_to_idx{$genre_artist_lists[$genre_idx][$selected]};
                $level = 2;
                $album_in_artist_idx = ($artist_idx == $current_artist_idx) ? $current_album_in_artist_idx : 0;
                $selected = $album_in_artist_idx;
                $in_playlist = 0;
            } elsif ($level == 2) {
                if ($in_playlist) {
                    $playlist_album_idx = $selected;
                    $album_idx = $playlist_album_idx;
                    $level = 3;
                    $selected = ($albums[$album_idx] eq $current_album) ? $current_track_idx : 0;
                } else {
                    $album_in_artist_idx = $selected;
                    $album_idx = $artist_album_lists[$artist_idx][$selected];
                    $level = 3;
                    if ($albums[$album_idx] eq $current_album) {
                        $selected = $current_track_idx;
                    } else {
                        $selected = 0;
                    }
                }
            } else {
                $did_select = 1;
                last;
            }
        }
    }

    my $result_album = '';
    my $result_offset = 0;
    if ($did_select) {
        $result_album = $albums[$album_idx];
        $result_offset = $track_offsets->[$selected] || 0;

        my $restore_album_path = $result_album;
        my $restore_track_file = $track_files->[$selected] // '';
        my $restore_album_num = -1;
        for my $i (0 .. $#albums) {
            if ($albums[$i] eq $restore_album_path) {
                $restore_album_num = $i + 1;
                last;
            }
        }
        &update_display($restore_album_num, $restore_album_path, $restore_track_file, scalar(@albums));
    } else {
        &restore_display();
    }

    # Menu is closing; drop the flag immediately so buttons drop out of
    # menu mode even if the result pipe is slow.
    unlink($menu_mode_file) if -e $menu_mode_file;

    # Write the result back to the caller through the FIFO.
    my $result = $did_select ? "album=$result_album\toffset=$result_offset" : "cancel=1";
    log_warn("writing result: $result");
    if (sysopen(my $out, $menu_out_fifo, O_WRONLY|O_NONBLOCK)) {
        syswrite($out, "$result\n");
        close($out);
    } else {
        log_warn("cannot write $menu_out_fifo: $!");
    }
}

# Clean up a stale menu_mode file from a previous/crashed run.
unlink($menu_mode_file) if -e $menu_mode_file;

# Open the command FIFO and wait for 'show' requests.
open(MENU_IN, '+<', $menu_in_fifo) or die "cannot open $menu_in_fifo: $!\n";
my $main_select = IO::Select->new(\*MENU_IN);

while (1) {
    my @ready = $main_select->can_read();
    next unless @ready;
    my $line = <MENU_IN>;
    next unless defined $line;
    chomp $line;
    $line =~ s/^\s+|\s+$//g;
    next unless $line eq 'show';
    log_warn("received show, running menu");

    my @play_albums = read_playlist_file($playlist_file);
    unless (@play_albums) {
        log_warn("No playlist file, showing generate menu");
    }

    my ($current_album, $current_offset) = read_current_album($current_album_file);
    my $current_album_idx = 0;
    for my $i (0 .. $#play_albums) {
        if ($play_albums[$i] eq $current_album) {
            $current_album_idx = $i;
            last;
        }
    }

    run_menu(\@play_albums, $current_album_idx);
}
 
