#!/bin/sh

DAEMON=/usr/lib/pidap/pidap-playlist

start() {
    /sbin/start-stop-daemon -S -b -x "$DAEMON"
}

stop() {
    /sbin/start-stop-daemon -K -x "$DAEMON"
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop; start ;;
    *) echo "Usage: $0 {start|stop|restart}" ;;
esac
exit $?
